### ISSUE TITLE
New VFS Team Member Template Your allison

### ISSUE THREAD

**Issue by allison0034** [allison0034/testyaml#1]
### Your name

allison

### Role

design

### Email

dfgdfgdf

### GitHub handle

dffg

### Start date

dfgfd

### VFS team

dfgdfg

### Tasks for all

- [ ] Add your name to the ticket title
- [ ] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)
- [ ] Request [access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
- [X] Confirm that you have access to the [VA GitHub Organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization).\n**Note** Membership in the VA Github Organization is a prerequisite for getting access to vets.gov-write and access to many commonly-used repositories. Platform will not be able to complete this task if you are not a member of the VA GitHub Organization.
- [ ] Opt out of [Google Analytics](https://www.va.gov/analytics-opt-out.html) on all of your browsers on your work machines, personal machines (if you are not a Veteran yourself using the site for your own applications), and mobile devices
- [ ] Are you a Veteran? Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document

### Tasks for Front-end and Back-end Engineers

- [ ] Confirm that [you can log in as a test user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

### Tasks for Product Managers & Delivery Managers

- [ ] Schedule a PM intro via [Calendly](https://calendly.com/collaboration-cycle/product-manager-intro) with Shira Goodman (Platform Governance Team PM).
- [ ] If your team is new, please complete the [New VFS Team ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteams). If you're joining an existing team, you can skip this step.
